import { describe, expect, it } from 'vitest';
import { testSession } from './helpers.js';

function guild() { const h=testSession('contracts'); h.commands.foundTown(); for(let i=0;i<4;i++)h.debug.spawnHunter({level:20,fullyEquipped:true}); return h; }
describe('contracts and factions (REQ-CON-001/REQ-FAC-001)',()=>{
  it('analyses offers before acceptance with client, risk and reward reasons',()=>{const h=guild();const board=h.commands.contractBoard();expect(board.length).toBeGreaterThan(0);expect(board[0]?.offer.clientName).toBeTruthy();expect(board[0]?.reasons.join(' ')).toMatch(/level|offers/);});
  it('accepts only one active contract and resolves it through a real expedition',()=>{const h=guild();const offer=h.commands.contractBoard().find(x=>x.offer.regionId==='verdant_reach')!.offer;expect(h.commands.acceptContract(offer.offerId).ok).toBe(true);expect(h.commands.acceptContract(h.commands.contractBoard()[0]!.offer.offerId).ok).toBe(false);const gold=h.session.resources.amount('gold');const outcome=h.commands.sendExpedition(offer.regionId,offer.objective);expect(outcome.ok).toBe(true);expect(h.session.contracts.active()).toBeUndefined();if(outcome.ok&&outcome.value.result.completed)expect(h.session.resources.amount('gold')).toBeGreaterThan(gold);});
  it('updates faction standing and hunter chronicles on success',()=>{const h=guild();const offer=h.commands.contractBoard().find(x=>x.offer.regionId==='verdant_reach')!.offer;h.commands.acceptContract(offer.offerId);const party=h.session.partyPlanner.propose(h.session.roster.all(),offer.objective);const outcome=h.commands.sendExpedition(offer.regionId,offer.objective,party);expect(outcome.ok).toBe(true);if(!outcome.ok)return;expect(h.session.factions.value(offer.factionId)).toBe(outcome.value.result.completed?3:-2);for(const member of party.members)expect(h.session.chronicle.counter(member.hunterId,outcome.value.result.completed?'contractsCompleted':'contractsFailed')).toBe(1);});
  it('persists offers, active contract and faction standing',()=>{const first=guild();const offer=first.commands.contractBoard()[0]!.offer;first.commands.acceptContract(offer.offerId);first.session.factions.change(offer.factionId,7);const second=testSession('contracts-load');second.session.restore(first.session.snapshot());expect(second.session.contracts.active()?.offerId).toBe(offer.offerId);expect(second.session.factions.value(offer.factionId)).toBe(7);});
});
